In [2]:
import numpy as np

## Data Types and Attributes

In [5]:
# Numpy's main data types is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.2, 3.3],
              [4, 5, 6.5]])


a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [6]:
a2

array([[1. , 2.2, 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.2  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2, 3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2, 3))       # shape of array whose each element is zero
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)     # start with zero, end with ten, stepsize of two
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 2, 0, 2, 9],
       [1, 3, 0, 4, 9],
       [7, 7, 3, 5, 2]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5, 3))     # all elements are between 0 to 1.
random_array_2 

array([[0.82275021, 0.73744501, 0.6423163 ],
       [0.35004469, 0.20297647, 0.78674761],
       [0.42023368, 0.99733545, 0.30672594],
       [0.12403611, 0.91537396, 0.39839557],
       [0.2009489 , 0.34435308, 0.00211827]])

In [35]:
random_array_2 .shape

(5, 3)

In [37]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.9637839 , 0.78087493, 0.92047923],
       [0.5559965 , 0.59615551, 0.02596439],
       [0.34944955, 0.18842748, 0.39798841],
       [0.48606153, 0.2835391 , 0.32752789],
       [0.83054207, 0.87581776, 0.79399148]])

In [ ]:
# Pseudo-random numbers

In [48]:
np.random.seed(7)

        # this can fix reproduce same array at every time
random_array_4 = np.random.random((5, 3))
random_array_4

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [49]:
np.random.seed(seed=99999)
random_array_5 = np.random.randint(10, size=(5, 3))
random_array_5

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

## 3. Viewing Arrays and matrices

In [50]:
np.unique(random_array_5)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [7]:
a1

array([1, 2, 3])

In [52]:
a2

array([[1. , 2.2, 3.3],
       [4. , 5. , 6.5]])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1[0]

1

In [9]:
a2[0]

array([1. , 2.2, 3.3])

In [10]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a2[1]

array([4. , 5. , 6.5])

In [12]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [13]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4


array([[[[6, 2, 5, 4, 0],
         [9, 0, 9, 8, 4],
         [2, 8, 6, 7, 5],
         [8, 0, 0, 0, 7]],

        [[6, 1, 9, 6, 7],
         [0, 0, 7, 1, 3],
         [2, 5, 9, 9, 0],
         [1, 0, 4, 7, 5]],

        [[3, 1, 9, 4, 1],
         [5, 9, 8, 6, 7],
         [9, 5, 7, 1, 9],
         [2, 1, 4, 9, 6]]],


       [[[5, 8, 4, 0, 1],
         [3, 6, 2, 0, 5],
         [7, 0, 7, 5, 4],
         [4, 5, 6, 9, 3]],

        [[7, 2, 7, 6, 0],
         [6, 2, 3, 5, 3],
         [0, 6, 0, 5, 4],
         [6, 3, 1, 4, 8]],

        [[5, 7, 9, 0, 5],
         [5, 0, 4, 2, 0],
         [5, 1, 1, 2, 0],
         [1, 7, 9, 1, 8]]]])

In [14]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [16]:
a4 = np.random.randint(10, size=(2, 3, 4, 5, 6))
a4

array([[[[[5, 7, 4, 0, 7, 3],
          [9, 4, 3, 9, 8, 4],
          [0, 3, 9, 7, 9, 7],
          [6, 5, 8, 9, 7, 0],
          [1, 0, 3, 9, 5, 5]],

         [[6, 1, 8, 4, 5, 4],
          [3, 7, 2, 8, 1, 6],
          [2, 8, 2, 3, 0, 7],
          [3, 8, 0, 5, 6, 3],
          [1, 2, 7, 7, 4, 0]],

         [[2, 7, 9, 5, 3, 8],
          [7, 9, 8, 6, 5, 1],
          [0, 9, 1, 7, 9, 9],
          [4, 1, 3, 3, 9, 6],
          [4, 2, 4, 8, 5, 7]],

         [[9, 7, 9, 2, 8, 6],
          [7, 7, 7, 3, 0, 0],
          [9, 2, 2, 7, 4, 5],
          [8, 3, 5, 9, 0, 4],
          [1, 2, 4, 5, 6, 6]]],


        [[[5, 3, 7, 4, 8, 5],
          [8, 9, 9, 3, 3, 8],
          [1, 1, 5, 9, 7, 2],
          [8, 0, 2, 3, 3, 5],
          [9, 5, 2, 6, 6, 1]],

         [[9, 4, 9, 5, 1, 4],
          [8, 2, 2, 9, 2, 1],
          [4, 1, 1, 8, 2, 1],
          [1, 2, 3, 3, 7, 9],
          [5, 2, 5, 0, 6, 0]],

         [[8, 0, 4, 0, 6, 9],
          [9, 8, 4, 9, 5, 3],
          [2, 2, 9, 0, 4, 

In [17]:
# get the first four no of the inner most array

In [20]:
a4[:, :, :, :1]

array([[[[[5, 7, 4, 0, 7, 3]],

         [[6, 1, 8, 4, 5, 4]],

         [[2, 7, 9, 5, 3, 8]],

         [[9, 7, 9, 2, 8, 6]]],


        [[[5, 3, 7, 4, 8, 5]],

         [[9, 4, 9, 5, 1, 4]],

         [[8, 0, 4, 0, 6, 9]],

         [[9, 0, 5, 4, 5, 6]]],


        [[[3, 8, 8, 7, 4, 2]],

         [[2, 1, 0, 8, 7, 1]],

         [[2, 1, 3, 5, 8, 7]],

         [[1, 2, 0, 1, 3, 3]]]],



       [[[[0, 0, 0, 3, 4, 2]],

         [[9, 5, 9, 3, 3, 7]],

         [[7, 6, 2, 7, 7, 3]],

         [[9, 3, 2, 7, 3, 8]]],


        [[[6, 8, 5, 0, 8, 5]],

         [[6, 1, 5, 8, 0, 8]],

         [[0, 3, 3, 4, 5, 6]],

         [[1, 9, 7, 0, 5, 5]]],


        [[[5, 1, 0, 7, 0, 8]],

         [[4, 1, 4, 4, 2, 0]],

         [[8, 9, 0, 8, 9, 6]],

         [[0, 1, 1, 4, 9, 7]]]]])